# Generated by Django 3.1.5 on 2021-02-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Msg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ImageShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=20, null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('member_img', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
