# Generated by Django 3.1.5 on 2021-02-26 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prayosha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=10, null=True)),
                ('pro_type', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='imageshow',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prayosha.projects'),
        ),
    ]
